export const projects = [
    {
        slug: "chill-guy",
        title: "I'm a chill guy",
        description:
            "AI-based GitHub profile roaster that analyzes repositories and generates humorous, filtered AI responses.",
        image: "https://picsum.photos/1200/1600",
        technologies: [
            "React",
            "Express",
            "Gemini API",
            "GitHub API",
            "Tailwind CSS",
            "Vercel",
            "Netlify",
        ],
        timeline: "Ongoing",
        github: "https://github.com/ramxcodes/chill-guy",
        live: "https://chillguy.ramx.in",
        role: "Full Stack",
        team: "Solo",
        status: "Completed",
        featured: false,
        challenges: [
            "GitHub API rate limiting",
            "AI prompt engineering",
            "Response content filtering",
            "Performance optimization",
        ],
        learnings: [
            "Gemini API integration",
            "GitHub API data processing",
            "AI prompt optimization",
            "Content moderation techniques",
        ],
        isPublished: true,
        publishedOn: "12/06/2002",
    },

    {
        slug: "dumcel-cloud",
        title: "Dumcel Cloud",
        description:
            "A Vercel-like deployment platform for React apps built with a microservices architecture supporting automated builds and deployments.",
        image: "/project/dumcel.png",
        technologies: [
            "Next.js",
            "Node.js",
            "Docker",
            "AWS ECS",
            "Redis",
            "Kafka",
        ],
        github: "https://github.com/yourusername/dumcel",
        live: "",
        timeline: "Ongoing",
        role: "Backend + Platform",
        team: "Solo",
        status: "Open Source",
        featured: true,
        challenges: [
            "Distributed build orchestration",
            "Containerized deployments",
            "Real-time status tracking",
            "Log ingestion at scale",
        ],
        learnings: [
            "Microservices architecture",
            "AWS ECS deployment workflows",
            "Kafka-based pipelines",
            "Infrastructure design",
        ],
        isPublished: false,
        publishedOn: "12/06/2002",
    },

    {
        slug: "visly-analytics",
        title: "Visly Analytics",
        description:
            "A privacy-first web analytics platform with a lightweight SDK, real-time ingestion pipeline, and high-performance dashboards.",
        image: "/project/visly.png",
        technologies: [
            "Next.js",
            "Node.js",
            "Kafka",
            "Redis",
            "ClickHouse",
            "PostgreSQL",
        ],
        github: "https://github.com/yourusername/visly",
        live: "",
        timeline: "Ongoing",
        role: "Full Stack",
        team: "Solo",
        status: "Building",
        featured: true,
        challenges: [
            "High-throughput event ingestion",
            "Real-time analytics",
            "SDK design",
            "Data modeling for OLAP",
        ],
        learnings: [
            "Analytics system design",
            "ClickHouse query optimization",
            "SDK architecture",
            "Event-driven systems",
        ],
        isPublished: true,
        publishedOn: "12/06/2002",
    },

    {
        slug: "job-nextly",
        title: "Job Nextly",
        description:
            "An AI-powered job application tracker that analyzes job descriptions and helps manage applications efficiently.",
        image: "/project/jobnextly.png",
        technologies: [
            "Next.js",
            "Gemini API",
            "PostgreSQL",
            "Tailwind CSS",
            "Firebase",
        ],
        github: "https://github.com/yourusername/job-nextly",
        live: "",
        timeline: "Completed",
        role: "Full Stack",
        team: "Solo",
        status: "Completed",
        featured: false,
        challenges: [
            "AI response consistency",
            "Structured job data extraction",
            "UX for tracking workflows",
        ],
        learnings: [
            "AI-assisted productivity tools",
            "Prompt structuring",
            "Data modeling for tracking systems",
        ],
        isPublished: true,
        publishedOn: "12/06/2002",
    },

    {
        slug: "comic-portfolio",
        title: "Comic Portfolio",
        description:
            "A comic-themed developer portfolio with rich micro-interactions and animated storytelling.",
        image: "/project/portfolio.png",
        technologies: ["Next.js", "Framer Motion", "Tailwind CSS"],
        github: "https://github.com/yourusername/portfolio",
        live: "https://yourportfolio.com",
        timeline: "Completed",
        role: "Frontend",
        team: "Solo",
        status: "Live",
        featured: true,
        challenges: [
            "Balancing creativity with performance",
            "Animation-heavy UI optimization",
        ],
        learnings: [
            "Advanced Framer Motion patterns",
            "Interactive UI storytelling",
        ],
        isPublished: true,
        publishedOn: "12/06/2002",
    },
];
