// src/config/skills.ts
export const skills = [
  {
    id: "nextjs",
    name: "Next.js",
    src: "/skills/nextjs.png",
    isPublished: true,
    priority: 1,
  },
  {
    id: "aws",
    name: "AWS",
    src: "/skills/aws.png",
    isPublished: true,
    priority: 2,
  },
  {
    id: "css",
    name: "CSS",
    src: "/skills/css.png",
    isPublished: true,
    priority: 3,
  },
  {
    id: "docker",
    name: "Docker",
    src: "/skills/docker.png",
    isPublished: true,
    priority: 4,
  },
  {
    id: "express",
    name: "Express.js",
    src: "/skills/express.png",
    isPublished: true,
    priority: 5,
  },
  {
    id: "javascript",
    name: "JavaScript",
    src: "/skills/JavaScript.png", // Kept exact case from screenshot
    isPublished: true,
    priority: 6,
  },
  {
    id: "kafka",
    name: "Kafka",
    src: "/skills/kafka.png",
    isPublished: true,
    priority: 7,
  },
  {
    id: "mongodb",
    name: "MongoDB",
    src: "/skills/mongodb.png",
    isPublished: true,
    priority: 8,
  },
  {
    id: "mysql",
    name: "MySQL",
    src: "/skills/mysql.png",
    isPublished: true,
    priority: 9,
  },
  {
    id: "nodejs",
    name: "Node.js",
    src: "/skills/nodejs.png",
    isPublished: true,
    priority: 10,
  },
  {
    id: "redis",
    name: "Redis",
    src: "/skills/redis.png",
    isPublished: true,
    priority: 11,
  },
  {
    id: "drizzle",
    name: "Drizzle ORM",
    src: "/skills/drizzle.png",
    isPublished: true,
    priority: 12,
  },
  {
    id: "firebase",
    name: "Firebase",
    src: "/skills/firebase.png",
    isPublished: true,
    priority: 13,
  },
  {
    id: "git",
    name: "Git",
    src: "/skills/git.png",
    isPublished: true,
    priority: 14,
  },
  {
    id: "github",
    name: "GitHub",
    src: "/skills/github.png",
    isPublished: true,
    priority: 15,
  },
  {
    id: "githubactions",
    name: "GitHub Actions",
    src: "/skills/githubactions.png",
    isPublished: true,
    priority: 16,
  },
  {
    id: "java",
    name: "Java",
    src: "/skills/java.png",
    isPublished: true,
    priority: 17,
  },
  {
    id: "typescript",
    name: "TypeScript",
    src: "/skills/typescript.png",
    isPublished: true,
    priority: 18,
  },
  {
    id: "npm",
    name: "NPM",
    src: "/skills/npm.png",
    isPublished: true,
    priority: 19,
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    src: "/skills/postgresql.png",
    isPublished: true,
    priority: 20,
  },
  {
    id: "postman",
    name: "Postman",
    src: "/skills/postman.png",
    isPublished: true,
    priority: 21,
  },
  {
    id: "prisma",
    name: "Prisma",
    src: "/skills/prisma.png",
    isPublished: true,
    priority: 22,
  },
  {
    id: "react",
    name: "React",
    src: "/skills/react.png",
    isPublished: true,
    priority: 23,
  },
  {
    id: "redux",
    name: "Redux",
    src: "/skills/redux.png",
    isPublished: true,
    priority: 24,
  },
  {
    id: "sass",
    name: "Sass",
    src: "/skills/sass.png",
    isPublished: true,
    priority: 25,
  },
  {
    id: "socketio",
    name: "Socket.io",
    src: "/skills/socketio.png",
    isPublished: true,
    priority: 26,
  },
  {
    id: "tailwind",
    name: "Tailwind CSS",
    src: "/skills/tailwind.png",
    isPublished: true,
    priority: 27,
  },
  {
    id: "shadcn",
    name: "ShadCn",
    src: "/skills/shadcn.png",
    isPublished: true,
    priority: 28,
  },
  {
    id: "vite",
    name: "Vite",
    src: "/skills/vite.png",
    isPublished: true,
    priority: 29,
  },
  {
    id: "vscode",
    name: "VS Code",
    src: "/skills/vscode.png",
    isPublished: true,
    priority: 30,
  },
];
